[package]
name = "unblock-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
unblock-storage = { workspace = true }
unblock-sync = { workspace = true }
unblock-health = { workspace = true }
unblock-error = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }
