//! [`HealthError`] — the per-crate error enum (spine §2.1; D4).
//!
//! Health is **storage-free** in v1-lite (F3/D29): integrity rows arrive as `Vec<String>`, so this
//! enum **never** sees or names a libsql/backend type. It implements [`CodedError`] so the engine's
//! cfg-gated `EngineError::Health` source can forward `code()`/`hint()`/`context()` uniformly
//! (mirroring the `unblock-sync` → `EngineError::Sync` precedent).
//!
//! Each variant maps to an **existing** [`ErrorCode`] (spine §2.2 — health introduces no new code):
//! `Io → IoError` (exit 8), `IntegrityCheckFailed → DatabaseError` (exit 2),
//! `Serialize → InternalError` (exit 1).

use std::path::PathBuf;

use snafu::Snafu;
use unblock_error::{CodedError, ErrorCode};

/// The error surfaced by `unblock-health` (v1-lite).
///
/// Context selectors are generated by `#[derive(Snafu)]`. `run_doctor` is pure and infallible in
/// v1-lite, so these variants form the **contract surface** the v1.1 pipeline (recovery-evidence I/O,
/// report serialization) constructs; the exit-code mapping is pinned now so it is stable from day one.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub(crate)))]
pub enum HealthError {
    /// A filesystem probe (open/read/metadata) failed.
    #[snafu(display("I/O error on '{}': {source}", path.display()))]
    Io {
        /// The underlying I/O error.
        source: std::io::Error,
        /// The path being probed.
        path: PathBuf,
    },

    /// The integrity check reported one or more problem rows.
    ///
    /// v1-lite reports integrity problems as data inside a [`DoctorReport`](crate::DoctorReport)
    /// rather than raising this error; the variant exists so a future strict caller (v1.1) can fail
    /// hard on corruption via a single mapped [`ErrorCode::DatabaseError`].
    #[snafu(display("integrity check failed: {} problem row(s)", rows.len()))]
    IntegrityCheckFailed {
        /// The raw integrity problem rows.
        rows: Vec<String>,
    },

    // [v1.1] RecoveryEvidenceWrite { source, path } — a write failure preserving `.unblock/.recovery/`
    //        evidence (FR-16 full); maps to `ErrorCode::IoError`. Not built in v1-lite.
    /// Serializing a health report to JSON failed.
    #[snafu(display("serialization error: {source}"))]
    Serialize {
        /// The underlying serde error.
        source: serde_json::Error,
    },
}

impl HealthError {
    /// The stable [`ErrorCode`] this error maps to (spine §2.2/§2.3 — an existing code, never a new
    /// one).
    #[must_use]
    pub fn code(&self) -> ErrorCode {
        match self {
            Self::Io { .. } => ErrorCode::IoError,
            Self::IntegrityCheckFailed { .. } => ErrorCode::DatabaseError,
            Self::Serialize { .. } => ErrorCode::InternalError,
        }
    }
}

impl CodedError for HealthError {
    fn code(&self) -> ErrorCode {
        Self::code(self)
    }
    // `hint()`/`retryable()`/`context()` default (spine §2.1): health surfaces no self-correction
    // hint or structured payload beyond its already-sanitized `Display` message. The engine's
    // cfg-gated `Self::Health{source} => source.hint()/.context()` arms compile against these
    // defaults.
}

#[cfg(test)]
mod tests {
    use super::HealthError;
    use unblock_error::{CodedError, ErrorCode};

    #[test]
    fn io_maps_to_io_error_exit_8_and_carries_path() {
        let err = HealthError::Io {
            source: std::io::Error::other("boom"),
            path: "/ws/.unblock/unblock.db".into(),
        };
        assert_eq!(err.code(), ErrorCode::IoError);
        assert_eq!(err.code().exit_code(), 8);
        assert!(err.to_string().contains("unblock.db"));
    }

    #[test]
    fn integrity_check_failed_maps_to_database_error_exit_2() {
        let err = HealthError::IntegrityCheckFailed {
            rows: vec!["*** in database main ***".to_string()],
        };
        assert_eq!(err.code(), ErrorCode::DatabaseError);
        assert_eq!(err.code().exit_code(), 2);
    }

    #[test]
    fn serialize_maps_to_internal_error_exit_1() {
        let bad = serde_json::from_str::<serde_json::Value>("{").unwrap_err();
        let err = HealthError::Serialize { source: bad };
        assert_eq!(err.code(), ErrorCode::InternalError);
        assert_eq!(err.code().exit_code(), 1);
    }

    #[test]
    fn coded_error_bridge_agrees_with_inherent_code() {
        let err = HealthError::IntegrityCheckFailed { rows: Vec::new() };
        assert_eq!(<HealthError as CodedError>::code(&err), err.code());
        // Defaults: no hint, empty context, non-retryable (DatabaseError is not retryable).
        assert!(err.hint().is_none());
        assert!(err.context().is_empty());
        assert!(!err.retryable());
    }
}
