//! [`SyncError`] — the per-crate error enum for `unblock-sync` (spine §2.2/§2.3).
//!
//! Every variant maps to an exit-6 (`JSONL`/sync) or exit-8 (`I/O`/JSON) [`ErrorCode`]; storage
//! failures are absorbed via a `#[snafu(transparent)]` `Storage` source so **no libsql type ever
//! crosses this boundary** (spine §6 rule 2). It implements [`CodedError`] so the engine's cfg-gated
//! `EngineError::Sync` source can forward `code()`/`hint()`/`context()` uniformly (F-2/D23).

use std::path::PathBuf;

use snafu::Snafu;
use unblock_error::{CodedError, ErrorCode};
use unblock_storage::StorageError;

use crate::path::PathReject;

/// The error surfaced by every `unblock-sync` operation (export/import/preflight).
///
/// Context selectors are generated by `#[derive(Snafu)]`. The `Storage` variant is
/// `#[snafu(transparent)]` so a backend failure forwards its own `Display` + code without ever
/// naming a libsql type in this crate's public API.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub(crate)))]
pub enum SyncError {
    /// A sync path failed confinement/allowlist validation (NFR-7/8). `reason` is the precise
    /// rejected layer; the `.git`/`..`/symlink-escape checks are never relaxed by `allow_external`.
    #[snafu(display("path '{}' rejected: {reason:?}", path.display()))]
    PathTraversal {
        /// The offending path.
        path: PathBuf,
        /// Which defence layer rejected it.
        reason: PathReject,
    },

    /// The import file contains git conflict markers (`<<<<<<<`/`=======`/`>>>>>>>`) — FR-8/NFR-8.
    #[snafu(display("conflict markers present in '{}': {preview}", path.display()))]
    ConflictMarkers {
        /// The offending file.
        path: PathBuf,
        /// A short preview (first few markers) for the operator.
        preview: String,
    },

    /// A JSONL line failed to parse as an [`unblock_model::Issue`] (FR-8).
    #[snafu(display("JSONL parse error at line {line}: {source}"))]
    JsonlParse {
        /// The 1-based line number.
        line: usize,
        /// The underlying serde error.
        source: serde_json::Error,
    },

    /// A parsed record failed `IssueValidator::validate` before any DB mutation (FR-8).
    #[snafu(display("validation failed at line {line}: {detail}"))]
    ValidationFailed {
        /// The 1-based line number.
        line: usize,
        /// The validation detail.
        detail: String,
    },

    /// An id appears more than once within the import file (FR-8).
    #[snafu(display("duplicate id '{id}' at line {line}"))]
    DuplicateId {
        /// The 1-based line number of the duplicate.
        line: usize,
        /// The duplicated id.
        id: String,
    },

    /// An import found an existing id under [`crate::CollisionPolicy::Error`] (D23).
    #[snafu(display("import collision on existing id '{id}'"))]
    ImportCollision {
        /// The colliding id.
        id: String,
    },

    /// A prefix mismatch during a `bd`/import mapping (defined now; used at T2.5).
    #[snafu(display("prefix mismatch: expected '{expected}', found '{found}'"))]
    PrefixMismatch {
        /// The expected id prefix.
        expected: String,
        /// The prefix actually found.
        found: String,
    },

    /// A semantic sync conflict (defined now; used at v1.3 for sync-conflict
    /// diagnostics — no reconciliation, roadmap §4).
    #[snafu(display("sync conflict: {detail}"))]
    SyncConflict {
        /// The conflict detail.
        detail: String,
    },

    /// An `allow_external` override was requested WITHOUT a written reason (NFR-5/D30, forward seam).
    ///
    /// The reason gates `allow_external` at the sync boundary — an override that writes/reads outside
    /// `confine_root` MUST carry an operator-written reason (which then rides the NFR-13
    /// force-override/external-path INFO). Maps to the existing `ErrorCode::PathTraversal` (exit-6,
    /// the confine-root-override family; NO new code). Unreachable in v1 (`allow_external` is forced
    /// `false` on every write path); this is a forward seam.
    #[snafu(display("external-path override on '{}' requires a written reason", path.display()))]
    ExternalOverrideWithoutReason {
        /// The external path whose override was requested without a reason.
        path: PathBuf,
    },

    /// A filesystem operation (open/read/write/rename/fsync/`create_dir_all`) failed (NFR-4/5).
    #[snafu(display("I/O error {action} '{}': {source}", path.display()))]
    Io {
        /// The path involved.
        path: PathBuf,
        /// The action being performed (e.g. `"reading"`, `"renaming"`).
        action: &'static str,
        /// The underlying I/O error.
        source: std::io::Error,
    },

    /// Serializing an [`unblock_model::Issue`] to a JSONL line failed (FR-7).
    #[snafu(display("JSON encode error: {source}"))]
    JsonEncode {
        /// The underlying serde error.
        source: serde_json::Error,
    },

    /// The import file exceeds the ingestion size cap (FORK-3, NFR-18).
    #[snafu(display("file '{}' is {size} bytes, over the {cap}-byte cap", path.display()))]
    FileTooLarge {
        /// The offending file.
        path: PathBuf,
        /// The observed size in bytes.
        size: u64,
        /// The enforced cap in bytes.
        cap: u64,
    },

    /// A single JSONL line exceeds the per-line size cap (FORK-3, NFR-18).
    #[snafu(display("line {line} is {len} bytes, over the {cap}-byte cap"))]
    LineTooLong {
        /// The 1-based line number.
        line: usize,
        /// The observed line length in bytes (at least `cap + 1`).
        len: usize,
        /// The enforced cap in bytes.
        cap: usize,
    },

    /// A backend storage failure, absorbed transparently (no libsql type crosses this boundary).
    #[snafu(transparent)]
    Storage {
        /// The underlying storage failure.
        source: StorageError,
    },
}

impl SyncError {
    /// The stable [`ErrorCode`] this error maps to (spine §2.2/§2.3).
    ///
    /// exit-6 (JSONL/sync): `PathTraversal`, `ExternalOverrideWithoutReason` (both →
    /// `PathTraversal`), `ConflictMarkers`, `JsonlParse`, `ValidationFailed`, `DuplicateId`,
    /// `LineTooLong` → JSONL parse class; `ImportCollision`; `PrefixMismatch`; `SyncConflict`.
    /// exit-8 (I/O): `Io`, `FileTooLarge` → `IoError`; `JsonEncode` → `JsonError`. The `Storage`
    /// source forwards its own code.
    #[must_use]
    pub fn code(&self) -> ErrorCode {
        match self {
            Self::PathTraversal { .. } | Self::ExternalOverrideWithoutReason { .. } => {
                ErrorCode::PathTraversal
            }
            Self::ConflictMarkers { .. } => ErrorCode::ConflictMarkers,
            Self::JsonlParse { .. }
            | Self::ValidationFailed { .. }
            | Self::DuplicateId { .. }
            | Self::LineTooLong { .. } => ErrorCode::JsonlParseError,
            Self::ImportCollision { .. } => ErrorCode::ImportCollision,
            Self::PrefixMismatch { .. } => ErrorCode::PrefixMismatch,
            Self::SyncConflict { .. } => ErrorCode::SyncConflict,
            Self::Io { .. } | Self::FileTooLarge { .. } => ErrorCode::IoError,
            Self::JsonEncode { .. } => ErrorCode::JsonError,
            Self::Storage { source } => source.code(),
        }
    }

    /// Whether the failing operation is retryable — none of the 8 native sync codes are (they are all
    /// deterministic input/path/serialization failures); the `Storage` source forwards its own.
    #[must_use]
    pub fn is_retryable(&self) -> bool {
        self.code().is_retryable()
    }
}

impl CodedError for SyncError {
    fn code(&self) -> ErrorCode {
        Self::code(self)
    }
    // `hint()`/`context()` default to `None`/empty (spine §2.1) — sync surfaces no self-correction
    // hint or structured payload beyond its already-sanitized `Display` message; the `Storage`
    // source's own hint/context are not forwarded (sync owns a distinct, coarser boundary). The
    // engine's cfg-gated `Self::Sync{source} => source.hint()/.context()` arms compile uniformly
    // against these defaults.
}

#[cfg(test)]
mod tests {
    use super::SyncError;
    use crate::path::PathReject;
    use std::path::PathBuf;
    use unblock_error::{CodedError, ErrorCode};
    use unblock_storage::StorageError;

    #[test]
    fn native_variants_map_to_exit_6_or_8() {
        let cases: Vec<(SyncError, ErrorCode, u8)> = vec![
            (
                SyncError::PathTraversal {
                    path: PathBuf::from("/x/.git/y"),
                    reason: PathReject::GitComponent,
                },
                ErrorCode::PathTraversal,
                6,
            ),
            (
                SyncError::ConflictMarkers {
                    path: PathBuf::from("/x/i.jsonl"),
                    preview: "line 3: <<<<<<<".into(),
                },
                ErrorCode::ConflictMarkers,
                6,
            ),
            (
                SyncError::ValidationFailed {
                    line: 2,
                    detail: "title empty".into(),
                },
                ErrorCode::JsonlParseError,
                6,
            ),
            (
                SyncError::DuplicateId {
                    line: 5,
                    id: "ub-1".into(),
                },
                ErrorCode::JsonlParseError,
                6,
            ),
            (
                SyncError::LineTooLong {
                    line: 1,
                    len: 4_194_305,
                    cap: 4_194_304,
                },
                ErrorCode::JsonlParseError,
                6,
            ),
            (
                SyncError::ImportCollision { id: "ub-1".into() },
                ErrorCode::ImportCollision,
                6,
            ),
            (
                SyncError::PrefixMismatch {
                    expected: "ub".into(),
                    found: "bd".into(),
                },
                ErrorCode::PrefixMismatch,
                6,
            ),
            (
                SyncError::SyncConflict {
                    detail: "diverged".into(),
                },
                ErrorCode::SyncConflict,
                6,
            ),
            (
                // NFR-5/D30 forward seam: an external override without a written reason maps to the
                // existing `PathTraversal` (exit-6), no new code (spine §2.3 exit table unchanged).
                SyncError::ExternalOverrideWithoutReason {
                    path: PathBuf::from("/outside/issues.jsonl"),
                },
                ErrorCode::PathTraversal,
                6,
            ),
            (
                SyncError::Io {
                    path: PathBuf::from("/x/i.jsonl"),
                    action: "renaming",
                    source: std::io::Error::other("boom"),
                },
                ErrorCode::IoError,
                8,
            ),
            (
                SyncError::FileTooLarge {
                    path: PathBuf::from("/x/i.jsonl"),
                    size: 3_000_000_000,
                    cap: 2_147_483_648,
                },
                ErrorCode::IoError,
                8,
            ),
        ];
        for (err, code, exit) in cases {
            assert_eq!(err.code(), code, "{err:?}");
            assert_eq!(err.code().exit_code(), exit, "{err:?}");
            assert!(!err.to_string().is_empty(), "Display non-empty: {err:?}");
            // `is_retryable` follows the code — none of the native codes are retryable.
            assert!(!err.is_retryable(), "{err:?}");
        }
    }

    #[test]
    fn jsonl_parse_maps_to_exit_6() {
        let bad = serde_json::from_str::<unblock_model::Issue>("not json").unwrap_err();
        let err = SyncError::JsonlParse {
            line: 1,
            source: bad,
        };
        assert_eq!(err.code(), ErrorCode::JsonlParseError);
        assert_eq!(err.code().exit_code(), 6);
    }

    #[test]
    fn json_encode_maps_to_exit_8() {
        // Fabricate a serde error via a non-serializable-to-string map key is awkward; instead a
        // number-out-of-range parse error stands in for the JSON encode class code assertion.
        let bad = serde_json::from_str::<serde_json::Value>("{").unwrap_err();
        let err = SyncError::JsonEncode { source: bad };
        assert_eq!(err.code(), ErrorCode::JsonError);
        assert_eq!(err.code().exit_code(), 8);
    }

    #[test]
    fn storage_source_forwards_its_code() {
        let err: SyncError = StorageError::IssueNotFound { id: "ub-1".into() }.into();
        assert_eq!(
            <SyncError as CodedError>::code(&err),
            ErrorCode::IssueNotFound
        );
    }
}
