// catalogue.go owns the §10.3 MCP tool catalogue wiring on the
// backend side. The on-disk source of truth is catalogue.json
// (human-editable); the embedded wire form lives in catalogue.gen.go
// (generated by apps/api/cmd/gen-catalogue and committed to git).
//
// Regenerate after editing catalogue.json:
//
//   cd apps/api && go generate ./mcp/...
//
// CI drift guard (per AC #3 + SPEC §10.3 line 2509): after the
// regenerate step CI runs `git diff --exit-code apps/api/mcp/catalogue.gen.go`
// — a stale generated file fails the build.
//
// SPEC anchors:
//
//   - §10.3 — catalogue authoring contract; transitions[] empty in P01.
//   - SPEC.md §7.2 — dual-location contract (backend half is the
//     authoritative source; the Rust `crates/unblock-plugin/data/catalogue.json`
//     copy lands in P04 and the catalogue-drift CI test boots the
//     emulator + diffs them).
//   - SPEC.md §5.2.2 — 23 P01 tools inventory (round-16: +promote,
//     Tool 15; +milestone Tools 16–19; +label Tools 20–23; mirrored in
//     the gen-catalogue tool's expectedToolCount constant).
//
// The `mcp.meta_catalogue` MCP tool that serves Catalogue over the wire
// is **not** registered in P01 — it ships in P02 alongside the BLOCK
// conditions section.

package mcp

//go:generate go run encore.app/cmd/gen-catalogue -in catalogue.json -out catalogue.gen.go
